### ISSUE TITLE
Compilation complaints about missing parent POM.

### ISSUE THREAD

**Issue by jmborer** [apache/netbeans-mavenutils-nbm-maven-plugin#127]
At the top most POM, Maven looks for    

<parent>
        <groupId>org.apache.netbeans</groupId>
        <artifactId>netbeans-parent</artifactId>
        <version>4</version>
 </parent>

This artifact seems not available in central repo. What is it used for?

**Comment by mbien** [comment]
https://github.com/apache/netbeans-parent
