### ISSUE TITLE
nbm-maven-plugin Some tokens are not provided by included modules: org.netbeans.modules.nbjavac

### ISSUE THREAD

**Issue by arsi-apli** [apache/netbeans-mavenutils-nbm-maven-plugin#187]
When compiling an NB platform application that contains the java cluster, the compilation ends with an error:
`Some tokens required by included modules are not provided by included modules. The application will fail starting up. The missing tokens are:
   org.netbeans.modules.nbjavac          ref: [org.netbeans.modules.java.source.nbjavac]`

The problem is that in ANB, nbjavac is installed on the first launch of the application from the update center.
The solution is  add to variable CreateClusterAppMojo:defaultPlatformTokens string "org.netbeans.modules.nbjavac"...

If this change is OK, I can do a pull request..

**Comment by neilcsmith-net** [comment]
I assume for some reason you're using a version of the platform before RELEASE130?  I don't think this is a desirable change.

**Comment by neilcsmith-net** [comment]
Same as other issue, as this is only an issue with long time EOL versions, closing.
