### ISSUE TITLE
Bundle.class files not generated?

### ISSUE THREAD

**Issue by jmborer** [apache/netbeans-mavenutils-nbm-maven-plugin#200]
I just upgraded recently to NB 23 and wanted to investigate issues with JRebel. During the build of the sample project (see attached file), I ran into the issue that no Bundle class file was generated in my project even though it was found in the index cache.

Complete fresh install, sample project created with the NB 23 included wizard. No external plugin installed (yet), no "Compile on Save" enabled. 

Product Version: Apache NetBeans IDE 23
Java: 23; OpenJDK 64-Bit Server VM 23+37
Runtime: OpenJDK Runtime Environment 23+37
System: Mac OS X version 14.6.1 running on x86_64; UTF-8; en_CH (nb)
User directory: /Users/jeanmarc/Library/Application Support/NetBeans/23
Cache directory: /Users/jeanmarc/Library/Caches/NetBeans/23

Never seen this before and I am using NB platform since several years. The Bundle.class is not generated in the "generated-classes" folder, but for some reason NB23 sees it in its index cached files...

To reproduce, just compile the attached project. It will fail to build the Rebellion-sample module.

[Rebellion.zip](https://github.com/user-attachments/files/17185290/Rebellion.zip)
[output.log](https://github.com/user-attachments/files/17185294/output.log)

**Comment by jmborer** [comment]
Some additional information. Just tested on a Windows machine with the following setup:

Product Version: Apache NetBeans IDE 22
Updates: [Updates available](https://github.com/apache/netbeans-mavenutils-nbm-maven-plugin/issues/check-for-updates)
Java: 17.0.8.1; OpenJDK 64-Bit Server VM 17.0.8.1+1-LTS
Runtime: OpenJDK Runtime Environment 17.0.8.1+1-LTS
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)
User directory: C:\Users\borerjc\AppData\Roaming\NetBeans\22
Cache directory: D:\netbeans\cache\22

Here the Bundle.class is properly generated during the compile phase. See attached output of Maven with verbose output turned on.

[output.log](https://github.com/user-attachments/files/17186893/output.log)

**Comment by neilcsmith-net** [comment]
Yes, expected behaviour on JDK 23. Compiler needs configuring to process annotations.

**Comment by jmborer** [comment]
Wouldn't it no be a good idea that when the plugin detects JDK 23, it shall add the <proc>full</proc> directive or at least warn the user?
