### ISSUE TITLE
nbm-maven-plugin uses deprecated "localRepository" expression

### ISSUE THREAD

**Issue by ramiswailem** [apache/netbeans-mavenutils-nbm-maven-plugin#96]
When using Maven 3.9.1 the following warnings are logged when using the nbm-maven-plugin:
```
[INFO] --- nbm:14.0-SNAPSHOT:manifest (default-manifest) @ nbm_localRepository ---
[WARNING] Parameter 'localRepository' is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[INFO] NBM Plugin generates manifest

```

https://github.com/apache/maven/pull/1009

**Comment by ebarboni** [comment]
thanks for the report. We should fix that because it's debt for later migration to mvv4x, Maybe there are some equivalent issue on the NetBeans repo, not sure we catch them all.  cc/@mbien

**Comment by ebarboni** [comment]
@ramiswailem if you can make a try it would be nice. Closing was automatic and maybe too early.

**Comment by ramiswailem** [comment]
Thank You @ebarboni

LGTM. The warning is disappeared
